# --- teensy3
BOARD_TAG 	 = teensy31
ARDUINO_DIR = /home/jak/arduino-1.6.4
ARDUINO_LIBS = SPI Adafruit_ILI9340 Adafruit_GFX
OPTIMIZATION_LEVEL =s 
ARDUINO_PLATFORM_LIB_PATH = $(ARDUINO_DIR)/hardware/teensy/avr/libraries/
include $(ARDUINO_DIR)/Arduino-Makefile/Teensy.mk

